import json
import re
from typing import Dict, Any


def _escape_string_for_python(s: str) -> str:
    """
    Safely escape a string for inclusion in Python code.

    Uses repr() for safe escaping, then removes the outer quotes
    since we'll add our own.
    """
    if not s:
        return ""

    # Use repr() which handles all escaping properly
    escaped = repr(s)

    # Remove the outer quotes added by repr()
    # repr() adds ' or " depending on content
    if escaped.startswith("'") and escaped.endswith("'"):
        escaped = escaped[1:-1]
    elif escaped.startswith('"') and escaped.endswith('"'):
        escaped = escaped[1:-1]

    # Now we need to escape single quotes since we use single quotes
    # repr() escapes them as \' which is correct
    return escaped


def _sanitize_identifier(s: str) -> str:
    """Sanitize a string to be a valid Python identifier."""
    if not s:
        return "unnamed"
    # Replace non-alphanumeric with underscore
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', s)
    # Ensure doesn't start with digit
    if sanitized and sanitized[0].isdigit():
        sanitized = '_' + sanitized
    return sanitized or "unnamed"


class WorkflowExporter:
    """
    Generates standalone Python code from a workflow dictionary.

    Security improvements:
    - Proper string escaping using repr()
    - Input validation for identifiers
    - Safe JSON serialization
    """

    @staticmethod
    def generate_script(workflow_data: Dict[str, Any]) -> str:
        """
        Generate a Python script that reconstructs and executes the workflow.
        """
        nodes = workflow_data.get('nodes', {})
        edges = workflow_data.get('edges', [])
        name = _escape_string_for_python(workflow_data.get('name', 'Exported Workflow'))
        description = _escape_string_for_python(workflow_data.get('description', ''))
        
        # Header imports
        script = [
            "# Auto-generated by Multi-Agent Orchestrator",
            "import asyncio",
            "import os",
            "from core.workflow import Workflow, WorkflowNode, WorkflowEdge, WorkflowEngine, NodeType, NodeStatus, AgreementRule",
            "",
            "async def main():",
            "    # 1. Initialize Workflow",
            f"    workflow = Workflow(name='{name}', description='{description}')",
            "",
            "    print(f' Initializing workflow: {{workflow.name}}')",
            "",
            "    # 2. Add Nodes"
        ]
        
        # Normalize nodes to a dictionary if they are a list
        if isinstance(nodes, list):
            nodes_dict = {}
            for i, node in enumerate(nodes):
                node_id = node.get('id', f"node_{i}")
                nodes_dict[node_id] = node
            nodes = nodes_dict

        # Add nodes
        for node_id, node in nodes.items():
            # Sanitize node_id to be a safe identifier
            safe_node_id = _sanitize_identifier(node_id)

            # Extract fields with safe escaping
            n_name = _escape_string_for_python(node.get('name', 'Node'))
            n_type = _escape_string_for_python(node.get('type', 'agent'))
            n_persona = _escape_string_for_python(node.get('persona', ''))
            n_provider = _escape_string_for_python(node.get('provider', 'mock'))
            n_model = _escape_string_for_python(node.get('model', 'default'))
            n_backstory = _escape_string_for_python(node.get('backstory', ''))

            # Complex fields need json serialization (json.dumps handles escaping)
            n_provider_config = node.get('provider_config', {})
            n_agreement_rules = node.get('agreement_rules', [])
            n_sub_workflows = node.get('sub_workflows', [])
            n_tier_config = node.get('tier_config', {})
            n_memory_config = node.get('memory_config', {"action": "store"})

            # Optional fields with safe escaping
            n_script_code = _escape_string_for_python(node.get('script_code', ""))
            
            script.append(f"    # Node: {n_name}")
            script.append(f"    workflow.add_node(WorkflowNode(")
            script.append(f"        id='{_escape_string_for_python(node_id)}',")
            script.append(f"        name='{n_name}',")
            script.append(f"        type='{n_type}',")  # Enum will be cast from string automatically by Pydantic if valid
            script.append(f"        persona='{n_persona}',")
            script.append(f"        provider='{n_provider}',")
            script.append(f"        model='{n_model}',")
            script.append(f"        backstory='{n_backstory}',")
            script.append(f"        requires_approval={bool(node.get('requires_approval', False))},")
            script.append(f"        save_enabled={bool(node.get('save_enabled', False))},")
            if node.get('save_path'):
                script.append(f"        save_path='{_escape_string_for_python(node.get('save_path'))}',")
            script.append(f"        max_iterations={int(node.get('max_iterations', 1))},")
            script.append(f"        internet_access={bool(node.get('internet_access', True))},")
            script.append(f"        tier='{_escape_string_for_python(node.get('tier', 'free'))}',")
            script.append(f"        token_budget={int(node.get('token_budget', 4096))},")
            script.append(f"        provider_config={json.dumps(n_provider_config)},")
            if n_agreement_rules:
                # Reconstruct AgreementRule objects with safe escaping
                rules_parts = []
                for r in n_agreement_rules:
                    r_name = _escape_string_for_python(r.get('name', ''))
                    r_type = _escape_string_for_python(r.get('type', ''))
                    r_value = _escape_string_for_python(r.get('value', ''))
                    r_required = bool(r.get('required', False))
                    rules_parts.append(
                        f"AgreementRule(name='{r_name}', type='{r_type}', value='{r_value}', required={r_required})"
                    )
                rules_str = "[" + ", ".join(rules_parts) + "]"
                script.append(f"        agreement_rules={rules_str},")

            script.append(f"        sub_workflows={json.dumps(n_sub_workflows)},")
            script.append(f"        tier_config={json.dumps(n_tier_config)},")
            script.append(f"        memory_config={json.dumps(n_memory_config)},")
            if n_script_code:
                script.append(f"        script_code='{n_script_code}',")

            script.append(f"        x={int(node.get('x', 0))},")
            script.append(f"        y={int(node.get('y', 0))}")
            script.append(f"    ))")
            script.append("")

        # Add edges
        script.append("    # 3. Add Edges")
        for edge in edges:
            source = _escape_string_for_python(edge.get('source', ''))
            target = _escape_string_for_python(edge.get('target', ''))
            label = _escape_string_for_python(edge.get('label', ''))
            feedback = bool(edge.get('feedback', False))

            script.append(f"    workflow.add_edge(WorkflowEdge(")
            script.append(f"        source='{source}',")
            script.append(f"        target='{target}',")
            script.append(f"        label='{label}',")
            script.append(f"        feedback={feedback}")
            script.append(f"    ))")
        
        # Execution
        script.append("")
        script.append("    # 4. Execute")
        script.append("    engine = WorkflowEngine()")
        script.append("    initial_input = input('Enter initial prompt/input: ')")
        script.append("    result = await engine.execute(workflow, initial_input=initial_input)")
        script.append("")
        script.append("    if result['success']:")
        script.append("        print('\\n[OK] Workflow Completed Successfully!')")
        script.append("        for node_id, data in result['nodes'].items():")
        script.append("            print(f\"--- Node {node_id} Output ---\")")
        script.append("            print(str(data['output'])[:500] + '...')")
        script.append("    else:")
        script.append("        print('\\n[FAIL] Workflow Failed')")

        script.append("")
        script.append("if __name__ == '__main__':")
        script.append("    asyncio.run(main())")
        
        return "\n".join(script)
